cleanup

diff --git a/bin/w b/bin/w
--- a/bin/w
+++ b/bin/w
@@ -1,16 +1,19 @@
-#!/bin/sh
+#!/bin/bash
 
-if [ -e /dev/shm ]; then
+if [[ -e /dev/shm ]]; then
   tmp="/dev/shm"
 else
   tmp="/tmp"
 fi
 
+(( RANDOM % 10 == 0 )) && {
+  # occasionally clean up
+  find "$tmp" -name 'wizard.*' -type f -mtime +30 -delete &
+  disown
+}
+
 tmp="$(mktemp "$tmp"/wizard.XXXXXXXXXXXXXXXXXXXXXX)"
+trap 'rm -f $tmp' EXIT
 cp "$(command -v wizard)" "$tmp"
 
 bash "$tmp" "$@"
-ret=$?
-
-rm -f "$tmp"
-exit "$ret"
