Refactoring, cleanup after changes

diff --git a/qcrypt b/qcrypt
--- a/qcrypt
+++ b/qcrypt
@@ -1,19 +1,13 @@
 #!/bin/bash
 
-# Script that compresses and encrypts directories or files with openssl and zip
+# Script that compresses and encrypts directories or files with openssl and tar
 # also handles the reverse process to restore the files. Works on files and
 # directories, don't have to be in the current working directory
 #
-# requires: openssl, md5sum, zip or tar
+# requires: openssl, md5sum, tar
 # author  : leaf@anardil.net
 
-set -u -o pipefail
-usage="usage: $0 (-a|-e|-d) (directory)"
-error () { for msg in "$@"; do echo "$msg"; done; exit 1; }
-
-# compress and then aes256 encrypt
-# =============================
-function encrypt() {
+function qencrypt() {
 
   file="$1"
   local sum
@@ -53,12 +47,9 @@ function encrypt() {
   if [[ "${QCRYPT_MODE:-}" == "TEST" ]]; then
     echo "!!! qcrypt test mode"
     openssl aes256 -in "$file.tar" -out "$file.qaes256" -salt -k "default"
-
   else
     openssl aes256 -in "$file.tar" -out "$file.qaes256" -salt 2>/dev/null
   fi
-
-  # check for encryption failure
   (( $? )) && {
     rm -rf "$file.tar" ./*.qcrypt
     error "!!! Encryption failed, not continuing."
@@ -70,26 +61,18 @@ function encrypt() {
   echo "+++ Encryption completed. Output file is $file.qaes256"
 }
 
-
-# aes256 decrypt and decompress
-# =============================
-function decrypt() {
-
+function qdecrypt() {
   file="$1"
   local file_ext out_file date sum
-
   date="date information not found"
   file_ext=""; [[ ${#file} -gt 8 ]] && file_ext=${file: -8}
 
   case $file_ext in
-    '.qaes256')
-      out_file=${file::-8}
-      ;;
+    '.qaes256') out_file=${file::-8} ;;
     *)
       echo    "??? $file doesn't appear to be encrypted by qcrypt. "
       read -p "    Are you sure you want to continue? (y/n) " -n 2 -r
       [[ 'Yy' =~ $REPLY ]] || exit
-
       out_file="$file"
       ;;
   esac
@@ -98,16 +81,10 @@ function decrypt() {
   if [[ "${QCRYPT_MODE:-}" == "TEST" ]]; then
     echo "!!! qcrypt test mode"
     openssl aes256 -d -in "$file" -out "$file.tar" -salt -k "default"
-
   else
     openssl aes256 -d -in "$file" -out "$file.tar" -salt 2>/dev/null
   fi
-
-  # check for decryption failure
-  (( $? )) && {
-    rm -f "$file.tar"
-    error "!!! Decryption failed, not continuing."
-  }
+  (( $? )) && { rm -f "$file.tar"; error "!!! Decryption failed, quiting."; }
 
   # check for overwrite
   [[ -e "$out_file" ]] && {
@@ -118,15 +95,12 @@ function decrypt() {
 
   # decompress the output
   tar -xf "$file".tar >/dev/null 2>/dev/null
-  (( $? )) && {
-    rm -f "$file.tar"
-    error "!!! Decompression failed, not continuing."
-  }
+  (( $? )) && { rm -f "$file.tar"; error "!!! Untar failed, quiting."; }
 
-  # attempt to grab date of encryption
+  # verify integrity
   [[ -e "date.qcrypt" ]] && date=$(cat date.qcrypt)
 
-  if [[ -e "md5sum.qcrypt" ]]; then
+  if [[ -e "md5sum.qcrypt" && -e "$out_file" ]]; then
     sum=$(find "$out_file" -type f -exec md5sum {} \; |
           sort -k 34 | md5sum | cut -c 1-32)
 
@@ -134,7 +108,6 @@ function decrypt() {
       rm -f "$file.tar" ./*.qcrypt
       error "!!! File integrity checks failed."
     }
-
   else
     echo "??? Cannot find file integrity check, unable to verify integrity."
   fi
@@ -146,34 +119,30 @@ function decrypt() {
 
 
 main () {
-
+  set -u -o pipefail
   local file auto_ext
+  usage="usage: $0 (-a|-e|-d) (directory)"
+  error () { for msg in "$@"; do echo "$msg"; done; exit 1; }
 
   for program in "openssl" "md5sum" "tar"; do
     [[ -z "$(which $program)" ]] && error "!!! Requires $program"
   done
 
-  # usage
   flag=${1:-}; file=${2:-}; arg3=${3:-}
-
   [[ $flag =~ -a|-e|-d ]] || error "$usage"
   [[ -z "$file" ]] && error "$usage"
   [[ -e "$file" ]] || error "!!! File provided does not exist."
   [[ -z "$arg3" ]] || error "!!! qcrypt only handles one directory at a time"
-
-  # remove trailing slash, if any
   file=${file%/}
 
   case $flag in
-    '-e') encrypt "$file" ;;
-    '-d') decrypt "$file" ;;
+    '-e') qencrypt "$file" ;;
+    '-d') qdecrypt "$file" ;;
     *)
-      # check if file name is long enough for qcrypt ext check
       auto_ext=${file: -8}; [[ ${#file} -le 8 ]] && auto_ext=""
-
       case $auto_ext in
-        '.qaes256') echo "Attempting decryption"; decrypt "$file" ;;
-        *)          echo "Attempting encryption"; encrypt "$file" ;;
+        '.qaes256') echo "Attempting decryption"; qdecrypt "$file" ;;
+        *)          echo "Attempting encryption"; qencrypt "$file" ;;
       esac
       ;;
   esac
